// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvdspnuemivovajusdbu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2ZHNwbnVlbWl2b3ZhanVzZGJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyOTA4MjksImV4cCI6MjA2Nzg2NjgyOX0.i2DXPqz90ckfqmeeyOv4RlsBNt4fFawPEK9SgQuC5ww";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});